package cl.tickers.app.parity

import cl.tickers.app.domain.engine.MortgageEngine
import cl.tickers.app.domain.model.MortgageInput
import cl.tickers.app.domain.model.Prepayment
import cl.tickers.app.domain.model.PrepaymentMode
import cl.tickers.app.domain.model.RateConvention
import com.google.common.truth.Truth.assertThat
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Test
import java.io.File
import java.math.BigDecimal
import java.math.RoundingMode
import java.time.LocalDate

/**
 * The two implementations of this app do the same arithmetic in two languages.
 * A label that differs between them is visible; a dividend that differs by a
 * hundredth is not, and it is the one that costs someone money.
 *
 * `shared/golden/mortgage.json` is the contract. It is not generated by either
 * side: both read it and both must agree with it exactly, at the engines' own
 * scale. Changing the engine on purpose means changing the file once, and then
 * both suites confirm the change landed on both platforms.
 *
 * The web counterpart is web/src/domain/__tests__/goldenVectors.test.ts.
 */
class GoldenVectorTest {

    private val golden: JsonObject = Json
        .parseToJsonElement(File("../shared/golden/mortgage.json").readText())
        .jsonObject

    private val moneyScale = golden["moneyScale"]!!.jsonPrimitive.content.toInt()
    private val rateScale = golden["rateScale"]!!.jsonPrimitive.content.toInt()

    private fun BigDecimal.money(): String =
        setScale(moneyScale, RoundingMode.HALF_UP).toPlainString()

    private fun BigDecimal.rate(): String =
        setScale(rateScale, RoundingMode.HALF_UP).toPlainString()

    private fun JsonObject.str(key: String): String = this[key]!!.jsonPrimitive.content
    private fun JsonObject.dec(key: String): BigDecimal = BigDecimal(str(key))

    private fun inputOf(o: JsonObject) = MortgageInput(
        propertyValueUf = o.dec("propertyValueUf"),
        downPaymentUf = o.dec("downPaymentUf"),
        annualRatePct = o.dec("annualRatePct"),
        termYears = o.str("termYears").toInt(),
        rateConvention = RateConvention.valueOf(o.str("rateConvention")),
        lifeInsuranceMonthlyPct = o.dec("lifeInsuranceMonthlyPct"),
        fireInsuranceMonthlyUf = o.dec("fireInsuranceMonthlyUf"),
        originationFeeUf = o.dec("originationFeeUf"),
        stampTaxPct = o.dec("stampTaxPct"),
        otherUpfrontCostsUf = o.dec("otherUpfrontCostsUf"),
        firstPaymentDate = LocalDate.parse(o.str("firstPaymentDate")),
        prepayments = o["prepayments"]!!.jsonArray.map {
            val p = it.jsonObject
            Prepayment(
                monthNumber = p.str("monthNumber").toInt(),
                amountUf = p.dec("amountUf"),
                mode = PrepaymentMode.valueOf(p.str("mode")),
            )
        },
    )

    @Test
    fun `every golden case matches the shared fixture`() {
        val cases = golden["cases"]!!.jsonArray
        assertThat(cases).isNotEmpty()

        for (element in cases) {
            val case = element.jsonObject
            val name = case.str("name")
            val expected = case["expected"]!!.jsonObject
            val result = MortgageEngine.simulate(inputOf(case["input"]!!.jsonObject))

            fun check(field: String, actual: String) {
                assertThat("$name / $field = $actual")
                    .isEqualTo("$name / $field = ${expected.str(field)}")
            }

            check("loanAmountUf", result.loanAmountUf.money())
            check("monthlyRate", result.monthlyRate.rate())
            check("basePaymentUf", result.basePaymentUf.money())
            check("firstTotalPaymentUf", result.firstTotalPaymentUf.money())
            check("totalInterestUf", result.totalInterestUf.money())
            check("totalLifeInsuranceUf", result.totalLifeInsuranceUf.money())
            check("totalFireInsuranceUf", result.totalFireInsuranceUf.money())
            check("totalPrepaymentsUf", result.totalPrepaymentsUf.money())
            check("upfrontCostsUf", result.upfrontCostsUf.money())
            check("totalCostUf", result.totalCostUf.money())
            check("scheduleLength", result.schedule.size.toString())
            check("effectiveTermMonths", result.effectiveTermMonths.toString())
            check("monthsSaved", result.monthsSaved.toString())

            val cae = expected["caePct"]!!.jsonPrimitive
            if (cae.content == "null") {
                assertThat(result.caePct).isNull()
            } else {
                check("caePct", result.caePct!!.money())
            }

            for ((number, rowElement) in expected["rows"]!!.jsonObject) {
                val row = rowElement.jsonObject
                val actual = result.schedule[number.toInt() - 1]

                fun checkRow(field: String, value: String) {
                    assertThat("$name / cuota $number / $field = $value")
                        .isEqualTo("$name / cuota $number / $field = ${row.str(field)}")
                }

                checkRow("number", actual.number.toString())
                checkRow("date", actual.date.toString())
                checkRow("openingBalanceUf", actual.openingBalanceUf.money())
                checkRow("interestUf", actual.interestUf.money())
                checkRow("principalUf", actual.principalUf.money())
                checkRow("paymentUf", actual.paymentUf.money())
                checkRow("lifeInsuranceUf", actual.lifeInsuranceUf.money())
                checkRow("fireInsuranceUf", actual.fireInsuranceUf.money())
                checkRow("prepaymentUf", actual.prepaymentUf.money())
                checkRow("totalOutflowUf", actual.totalOutflowUf.money())
                checkRow("closingBalanceUf", actual.closingBalanceUf.money())
            }
        }
    }
}
